import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import App from '../components/App'
import Header from '../components/Header'
import Todos from '../components/Todos'

export default function Home() {
  return (
    <div >
      <Head>
        <title>limon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
      <App/> 
    </div>
  )
}
